------------------------------------------------------------
~ Â» ssh kipparis@kipparis.beget.tech                                  kip@kip-HP-Pavilion-Laptop-15-cc5xx
Welcome to LTD BeGet SSH Server 'maru'
Welcome to Ubuntu 12.04.5 LTS (GNU/Linux 4.9.132-0-beget-acl x86_64)

 * Documentation:  https://help.ubuntu.com/
Last login: Wed Dec 12 14:59:09 2018 from 85.143.228.158
kipparis@maru:~ [0] $ ssh localhost -p222
kipparis@localhost's password: 

Permission denied, please try again.
kipparis@localhost's password: 
Welcome to Ubuntu 12.04 LTS (GNU/Linux 4.9.132-0-beget-acl x86_64)

 * Documentation:  https://help.ubuntu.com/
(docker) kipparis@maru:~ [0] $ cd levelteleg/
(docker) kipparis@maru:~/levelteleg [0] $ source venv/bin/activate
(docker) kipparis@maru:~/levelteleg [0] $ ls
base  passenger_wsgi.py  public_html  __pycache__  tmp	venv
(docker) kipparis@maru:~/levelteleg [0] $ cd base/base/
(docker) kipparis@maru:~/levelteleg/base/base [0] $ ls
__init__.py  __pycache__  settings.py  urls.py	wsgi_back.py  wsgi.py
(docker) kipparis@maru:~/levelteleg/base/base [0] $ vim wsgi
(docker) kipparis@maru:~/levelteleg/base/base [0] $ vim wsgi.py 
(docker) kipparis@maru:~/levelteleg/base/base [0] $ cd ../../
(docker) kipparis@maru:~/levelteleg [0] $ ls
base  passenger_wsgi.py  public_html  __pycache__  tmp	venv
(docker) kipparis@maru:~/levelteleg [0] $ vim passenger_wsgi.py 
(docker) kipparis@maru:~/levelteleg [0] $ vim passenger_wsgi.py 
(docker) kipparis@maru:~/levelteleg [0] $ cd base/base
(docker) kipparis@maru:~/levelteleg/base/base [0] $ ls
__init__.py  __pycache__  settings.py  urls.py	wsgi_back.py  wsgi.py
(docker) kipparis@maru:~/levelteleg/base/base [0] $ vim settings.py 
(docker) kipparis@maru:~/levelteleg/base/base [0] $ vim settings.py 
(docker) kipparis@maru:~/levelteleg/base/base [0] $ ls
__init__.py  __pycache__  settings.py  urls.py	wsgi_back.py  wsgi.py
(docker) kipparis@maru:~/levelteleg/base/base [0] $ vim wsgi
(docker) kipparis@maru:~/levelteleg/base/base [0] $ vim wsgi.py
(docker) kipparis@maru:~/levelteleg/base/base [0] $ cd ~/levelteleg/
(docker) kipparis@maru:~/levelteleg [0] $ ls
base  passenger_wsgi.py  public_html  __pycache__  tmp	venv
(docker) kipparis@maru:~/levelteleg [0] $ vim passenger_wsgi.py 
(docker) kipparis@maru:~/levelteleg [0] $ cd base/base/
(docker) kipparis@maru:~/levelteleg/base/base [0] $ ls
__init__.py  __pycache__  settings.py  urls.py	wsgi_back.py  wsgi.py
(docker) kipparis@maru:~/levelteleg/base/base [0] $ vim wsgi.py 
(docker) kipparis@maru:~/levelteleg/base/base [0] $ cd ~/levelteleg/
(docker) kipparis@maru:~/levelteleg [0] $ vim passenger_wsgi.py 
(docker) kipparis@maru:~/levelteleg [0] $ touch tmp/restart.txt 
(docker) kipparis@maru:~/levelteleg [0] $ vim passenger_wsgi.py 
(docker) kipparis@maru:~/levelteleg [0] $ touch tmp/restart.txt 
(docker) kipparis@maru:~/levelteleg [0] $ python passenger_wsgi.py 
  File "passenger_wsgi.py", line 13
    ~                                                                                                         
                                                                                                             ^
SyntaxError: invalid syntax
(docker) kipparis@maru:~/levelteleg [1] $ vim passenger_wsgi.py 
(docker) kipparis@maru:~/levelteleg [0] $ python passenger_wsgi.py 
  File "passenger_wsgi.py", line 12
    ~                                                                                                         
                                                                                                             ^
SyntaxError: invalid syntax
(docker) kipparis@maru:~/levelteleg [1] $ vim passenger_wsgi.py 
(docker) kipparis@maru:~/levelteleg [0] $ python passenger_wsgi.py 
  File "passenger_wsgi.py", line 13
    ~                                                                                                         
                                                                                                             ^
SyntaxError: invalid syntax
(docker) kipparis@maru:~/levelteleg [1] $ vim passenger_wsgi.py 
(docker) kipparis@maru:~/levelteleg [0] $ cd base/base/
(docker) kipparis@maru:~/levelteleg/base/base [0] $ vim wsgi.py 
(docker) kipparis@maru:~/levelteleg/base/base [0] $ cd ../
(docker) kipparis@maru:~/levelteleg/base [0] $ python manage.py runserver
**********
AMA IN SETTIIIIIIINGS
**********
**********
AMA IN SETTIIIIIIINGS
**********
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f446c798f28>
Traceback (most recent call last):
  File "/home/k/kipparis/levelteleg/venv/lib/python3.6/site-packages/django/apps/registry.py", line 152, in get_app_config
    return self.app_configs[app_label]
KeyError: 'admin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/k/kipparis/levelteleg/venv/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/k/kipparis/levelteleg/venv/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "/home/k/kipparis/levelteleg/venv/lib/python3.6/site-packages/django/core/management/base.py", line 379, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/k/kipparis/levelteleg/venv/lib/python3.6/site-packages/django/core/management/base.py", line 366, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/k/kipparis/levelteleg/venv/lib/python3.6/site-packages/django/core/checks/registry.py", line 71, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/k/kipparis/levelteleg/venv/lib/python3.6/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/k/kipparis/levelteleg/venv/lib/python3.6/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/k/kipparis/levelteleg/venv/lib/python3.6/site-packages/django/urls/resolvers.py", line 396, in check
    for pattern in self.url_patterns:
  File "/home/k/kipparis/levelteleg/venv/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/k/kipparis/levelteleg/venv/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/k/kipparis/levelteleg/venv/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/k/kipparis/levelteleg/venv/lib/python3.6/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/k/kipparis/levelteleg/venv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/home/k/kipparis/levelteleg/base/base/urls.py", line 22, in <module>
    path('admin/', admin.site.urls),
  File "/home/k/kipparis/levelteleg/venv/lib/python3.6/site-packages/django/utils/functional.py", line 213, in inner
    self._setup()
  File "/home/k/kipparis/levelteleg/venv/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 526, in _setup
    AdminSiteClass = import_string(apps.get_app_config('admin').default_site)
  File "/home/k/kipparis/levelteleg/venv/lib/python3.6/site-packages/django/apps/registry.py", line 159, in get_app_config
    raise LookupError(message)
LookupError: No installed app with label 'admin'.
:q
^C(docker) kipparis@maru:~/levelteleg/base [0] $ cd base/
(docker) kipparis@maru:~/levelteleg/base/base [0] $ vim settings.py 
(docker) kipparis@maru:~/levelteleg/base/base [0] $ cd ../
(docker) kipparis@maru:~/levelteleg/base [0] $ python manage.py runserver
**********
AMA IN SETTIIIIIIINGS
**********
**********
AMA IN SETTIIIIIIINGS
**********
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f53960f2488>
Traceback (most recent call last):
  File "/home/k/kipparis/levelteleg/venv/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/k/kipparis/levelteleg/venv/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/home/k/kipparis/levelteleg/venv/lib/python3.6/site-packages/django/utils/autoreload.py", line 248, in raise_last_exception
    raise _exception[1]
  File "/home/k/kipparis/levelteleg/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 337, in execute
    autoreload.check_errors(django.setup)()
  File "/home/k/kipparis/levelteleg/venv/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/k/kipparis/levelteleg/venv/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/k/kipparis/levelteleg/venv/lib/python3.6/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/home/k/kipparis/levelteleg/venv/lib/python3.6/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/k/kipparis/levelteleg/venv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/home/k/kipparis/levelteleg/venv/lib/python3.6/site-packages/django/contrib/admin/models.py", line 5, in <module>
    from django.contrib.contenttypes.models import ContentType
  File "/home/k/kipparis/levelteleg/venv/lib/python3.6/site-packages/django/contrib/contenttypes/models.py", line 134, in <module>
    class ContentType(models.Model):
  File "/home/k/kipparis/levelteleg/venv/lib/python3.6/site-packages/django/db/models/base.py", line 95, in __new__
    "INSTALLED_APPS." % (module, name)
RuntimeError: Model class django.contrib.contenttypes.models.ContentType doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
^C(docker) kipparis@maru:~/levelteleg/base [0] $ cd base
(docker) kipparis@maru:~/levelteleg/base/base [0] $ ls
__init__.py  __pycache__  settings.py  urls.py	wsgi_back.py  wsgi.py
(docker) kipparis@maru:~/levelteleg/base/base [0] $ vim settings.py 
(docker) kipparis@maru:~/levelteleg/base/base [0] $ cd ..
(docker) kipparis@maru:~/levelteleg/base [0] $ python manage.py runserver
**********
AMA IN SETTIIIIIIINGS
**********
**********
AMA IN SETTIIIIIIINGS
**********
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f335586d730>
Traceback (most recent call last):
  File "/home/k/kipparis/levelteleg/venv/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/k/kipparis/levelteleg/venv/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "/home/k/kipparis/levelteleg/venv/lib/python3.6/site-packages/django/core/management/base.py", line 425, in check
    raise SystemCheckError(msg)
django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:

ERRORS:
admin.LogEntry.user: (fields.E300) Field defines a relation with model 'auth.User', which is either not installed, or is abstract.
admin.LogEntry.user: (fields.E307) The field admin.LogEntry.user was declared with a lazy reference to 'auth.user', but app 'auth' isn't installed.

System check identified 2 issues (0 silenced).
^C(docker) kipparis@maru:~/levelteleg/base [0] $ cd base
(docker) kipparis@maru:~/levelteleg/base/base [0] $ vim settings.py 
(docker) kipparis@maru:~/levelteleg/base/base [0] $ cd ..
(docker) kipparis@maru:~/levelteleg/base [0] $ python manage.py runserver
**********
AMA IN SETTIIIIIIINGS
**********
**********
AMA IN SETTIIIIIIINGS
**********
Performing system checks...

System check identified no issues (0 silenced).
December 12, 2018 - 13:21:31
Django version 2.1.4, using settings 'base.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
^C(docker) kipparis@maru:~/levelteleg/base [0] $ cd base/
(docker) kipparis@maru:~/levelteleg/base/base [0] $ python wsgi.py 
**********
AMA IN SETTIIIIIIINGS
**********
(docker) kipparis@maru:~/levelteleg/base/base [0] $ cd ../../
(docker) kipparis@maru:~/levelteleg [0] $ ls
base  passenger_wsgi.py  public_html  __pycache__  tmp	venv
(docker) kipparis@maru:~/levelteleg [0] $ python passenger_wsgi.py 
  File "passenger_wsgi.py", line 13
    ~                                                                                                         
                                                                                                             ^
SyntaxError: invalid syntax
(docker) kipparis@maru:~/levelteleg [1] $ cd base/base
(docker) kipparis@maru:~/levelteleg/base/base [0] $ ls
__init__.py  __pycache__  settings.py  urls.py	wsgi_back.py  wsgi.py
(docker) kipparis@maru:~/levelteleg/base/base [0] $ cp wsgi.py ../../passenget_wsgi.py
(docker) kipparis@maru:~/levelteleg/base/base [0] $ cd ../../
(docker) kipparis@maru:~/levelteleg [0] $ ls
base  passenger_wsgi.py  passenget_wsgi.py  public_html  __pycache__  tmp  venv
(docker) kipparis@maru:~/levelteleg [0] $ rm passenge
rm: Ð½ÐµÐ²Ð¾Ð·Ð¼Ð¾Ð¶Ð½Ð¾ ÑÐ´Ð°Ð»Ð¸ÑÑ 'passenge': No such file or directory
(docker) kipparis@maru:~/levelteleg [1] $ rm passenger_wsgi.py 
(docker) kipparis@maru:~/levelteleg [0] $ mv passenge{t,r}_wsgi.py 
(docker) kipparis@maru:~/levelteleg [0] $ ls
base  passenger_wsgi.py  public_html  __pycache__  tmp	venv
(docker) kipparis@maru:~/levelteleg [0] $ python passenger_wsgi.py 
**********
AMA IN SETTIIIIIIINGS
**********
(docker) kipparis@maru:~/levelteleg [0] $ touch tmp/restart.txt 
(docker) kipparis@maru:~/levelteleg [0] $ 
